### ISSUE TITLE
addfriend not working

### ISSUE THREAD

**Issue by QueenMko** [BjoernPetersen/BlockOwn#160]
After the new update, players can't break eachothers blocks even if they add them as friends.

**Comment by Nicewuerfel** [comment]
I can't recreate that issue right now. Are protection messages enabled? What messages do the players get when trying to break such a block?

**Comment by QueenMko** [comment]
They get the message "This block is protected by the server" or something :) I downloaded the version before the last one in the meantime.

Date: Sat, 16 Apr 2016 08:02:05 -0700

**Comment by Nicewuerfel** [comment]
Does [this version](https://pheasn-travis.s3.amazonaws.com/Nicewuerfel/BlockOwn/110/110.1/target/blockown-5.4.2-SNAPSHOT.jar) fix your issue?
